### ISSUE TITLE
project setup and folder structure

### ISSUE THREAD

**Issue by Dschaykib** [Dschaykib/kacadu#6]

**Comment by ChristianVogl** [comment]
I would suggest the following folder structure (based on the current code on the dev-branch and the current issues):

```
.
├── LICENSE
├── README.md
├── src
│   ├── css
│   │   └── style.css
│   ├── img
│   ├── index.html
│   └── js
│       └── app.js
└── test
```
This way we can add additional global files (e.g. package.json) to the root of the project without loosing the overview over the production code (residing in src).

**Comment by ChristianVogl** [comment]
Commits b95e243 and 5c2cc3b solved this issue.
